# Generated by Django 4.2.1 on 2023-09-21 13:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0002_organizationinvites'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=225, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=225, null=True, verbose_name='last name')),
                ('profile_pic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile pic')),
                ('email', models.EmailField(max_length=225, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='refresh token')),
                ('bank_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='bank number')),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='bank code')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='bank name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('lunch_credit_balance', models.CharField(max_length=50, verbose_name='lunch credit')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users_groups', to='auth.group', verbose_name='groups')),
                ('org_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='organisation name')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
