# Generated by Django 4.2.5 on 2023-09-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password_reset_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="password_reset_token",),
    ]
