# Generated by Django 4.2.5 on 2023-09-21 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='lunch_price',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='lunch_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
