# Generated by Django 4.2.5 on 2023-09-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_invitation_options_alter_organization_options_and_more'),
        ('organization', '0002_organizationinvites'),
    ]

    operations = [
    ]
