# Generated by Django 4.2.5 on 2023-09-22 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('redeemed', 'Redeemed'), ('not_redeemed', 'Not Redeemed')], default='not_redeemed', max_length=20, verbose_name='withdrawal status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='withdrawal amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='withdrawal timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated timestamp')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
