# Generated by Django 4.2.5 on 2023-09-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('withdrawals', '0002_withdrawal_updated_at_alter_withdrawal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
